services:
  - type: web
    name: dishshop
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn DishShop_New.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: DishShop_New.settings
