# Generated by Django 5.1.7 on 2025-07-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_modelitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_images/'),
        ),
        migrations.AlterField(
            model_name='modelitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='models/'),
        ),
    ]
